# Generated by Django 5.0.3 on 2024-03-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('line', models.CharField(max_length=50, verbose_name='Line')),
                ('machine_no', models.CharField(max_length=50, verbose_name='Machine No')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('operation', models.CharField(max_length=50, verbose_name='Operation')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
    ]
