# Generated by Django 5.0.3 on 2024-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('running-100ef', 'Productive'), ('running-below-100ef', 'Productive (<100%)'), ('connected-and-ready', 'Connected and Ready'), ('disconnected', 'Disconnected'), ('machine-not-in-use', 'Machine Not In Use'), ('alarm', 'Alarm'), ('not-ready-for-operation', 'Not Ready For Operation'), ('breakdown', 'Breakdown')], max_length=50, verbose_name='Status'),
        ),
    ]
