# Generated by Django 5.0.3 on 2024-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='operation',
            field=models.CharField(max_length=500, verbose_name='Operation'),
        ),
    ]
