# Generated by Django 5.0.3 on 2024-03-07 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='modified_at'),
            preserve_default=False,
        ),
    ]
