# Generated by Django 5.0.3 on 2024-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_machine_created_at_machine_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='manufacturer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='shop_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='shop_name'),
        ),
    ]
