# Generated by Django 3.2.12 on 2022-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inhouseInventory',
            fields=[
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('productSno', models.CharField(default=0, max_length=122)),
                ('level', models.CharField(default=0, max_length=122)),
                ('qpp', models.CharField(default=0, max_length=122)),
                ('dimension', models.CharField(default=0, max_length=122)),
                ('drawingno', models.CharField(default=0, max_length=122)),
                ('availableNos', models.CharField(default=0, max_length=122)),
                ('description', models.DateTimeField(null=True)),
                ('timein', models.DateTimeField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
