# Generated by Django 3.2.12 on 2022-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhouseinventory',
            name='description',
            field=models.CharField(default=0, max_length=122),
        ),
    ]
