# Generated by Django 3.2.12 on 2022-03-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatorname', models.CharField(max_length=122)),
                ('identity', models.CharField(max_length=122)),
                ('machine', models.CharField(max_length=122)),
                ('variant', models.CharField(max_length=122)),
                ('partname', models.CharField(max_length=122)),
                ('partno', models.CharField(max_length=122)),
                ('timein', models.DateTimeField(null=True)),
                ('timeout', models.DateTimeField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
