# Generated by Django 5.0.3 on 2024-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='machine',
        ),
        migrations.AddField(
            model_name='operation',
            name='machine',
            field=models.ManyToManyField(related_name='machine_id', to='machines.machine'),
        ),
    ]
