# Generated by Django 3.2.12 on 2022-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productionOrder',
            fields=[
                ('sno', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('orderRefNo', models.CharField(max_length=122)),
                ('orderVariant', models.CharField(max_length=122)),
                ('orderStartDate', models.DateField(null=True)),
                ('orderEndDate', models.DateField(null=True)),
                ('orderQuantity', models.CharField(max_length=122)),
                ('orderPriority', models.CharField(max_length=122)),
                ('currentDate', models.DateField()),
            ],
        ),
    ]
