# Generated by Django 3.2.13 on 2022-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionSchedualar', '0003_rename_componet_name_componentdetails_component_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='operationsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationName', models.CharField(max_length=300)),
                ('inputComponentsName', models.CharField(max_length=300)),
                ('outputComponentsName', models.CharField(max_length=300)),
                ('operationMachineName', models.CharField(max_length=300)),
                ('operationTime', models.CharField(max_length=300)),
            ],
        ),
    ]
