# Generated by Django 3.2.13 on 2022-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionSchedualar', '0004_operationsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdetails',
            name='predecessor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='componentdetails',
            name='successor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
