# Generated by Django 5.0.3 on 2024-03-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderRefNo', models.CharField(blank=True, max_length=122, null=True)),
                ('orderVariant', models.CharField(blank=True, max_length=122, null=True)),
                ('orderStartDate', models.DateField(null=True)),
                ('orderEndDate', models.DateField(null=True)),
                ('orderQuantity', models.CharField(blank=True, max_length=122, null=True)),
                ('orderPriority', models.CharField(blank=True, max_length=122, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=50, verbose_name='status')),
                ('created_at', models.DateField(auto_now=True, verbose_name='created_at')),
                ('modified_at', models.DateField(auto_now_add=True, verbose_name='modified_at')),
            ],
            options={
                'db_table': 'tb_production_orders',
            },
        ),
    ]
