# Generated by Django 5.0.3 on 2024-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='id',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='orderId',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='order_id'),
            preserve_default=False,
        ),
    ]
