# Generated by Django 5.0.3 on 2024-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='assembly_code')),
                ('item', models.CharField(blank=True, max_length=500, null=True, verbose_name='item_description')),
                ('drg_no', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='drawing_no')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
