# Generated by Django 5.0.3 on 2024-03-07 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_operation_machine_operation_machine'),
        ('products', '0003_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('input_items', models.ManyToManyField(related_name='input_items', to='products.product')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_id', to='operations.operation')),
                ('output_items', models.ManyToManyField(related_name='output_items', to='products.product')),
            ],
            options={
                'verbose_name': 'OperationProduct',
                'verbose_name_plural': 'OperationProducts',
            },
        ),
    ]
