# Generated by Django 5.0.3 on 2024-03-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_operationproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='products.product'),
        ),
    ]
